# roles/k3s_dev_environment/handlers/main.yml
- name: Reload systemd and restart k3s
  ansible.builtin.systemd:
    daemon_reload: true
    name: k3s
    state: restarted
  listen: Reload systemd and restart k3s

- name: Reload systemd and restart buildkitd
  ansible.builtin.systemd:
    name: buildkitd
    enabled: true
    state: started
    daemon_reload: true
  listen: Reload systemd and restart buildkitd

- name: UserReloginNeeded
  ansible.builtin.debug:
    msg: "ACTION REQUIRED: User '{{ k3s_dev_environment_dev_user }}' needs to log out and log back in for all group memberships and environment variables to take full effect."
