---
- name: Run group-specific playbook based on hostname
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - group_map.yml

  tasks:
    - name: Lookup group for current hostname
      ansible.builtin.set_fact:
        current_group: "{{ group_map[ansible_hostname] | default('unknown') }}"

    - name: Fail if hostname is not mapped
      ansible.builtin.fail:
        msg: "Hostname '{{ ansible_hostname }}' not mapped in group_map.yml"
      when: current_group == 'unknown'

    - name: Include the group-specific playbook
      ansible.builtin.include_tasks: "playbooks/{{ current_group }}.yml"
...
