- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - ansible.builtin.import_tasks: tasks/env.yml
    - ansible.builtin.import_tasks: tasks/coding.yml
    - ansible.builtin.import_tasks: tasks/music.yml
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - htop
          - mc
          - tmux
