- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/coding.yml
    - name: Install packages
      apt:
        pkg:
          - htop
          - mc
          - tmux
