- name: Install coding tools
  apt:
    pkg:
      - code # Visual Studio Code

- name: Install git
  apt:
    name: git
    state: latest
    update_cache: yes

- name: Update the repository cache and update package "nginx" to latest version using default release squeeze-backport
  apt:
    name: nginx
    state: latest
    update_cache: yes
