- name: Install coding tools
  apt:
    pkg:
      - apt-transport-https

- name: Add an Apt signing key, will not download if present
  apt_key:
    # id: 9FED2BCBDCD29CDF762678CBAED4B06F473041FA
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

# Add specified repository into sources list using specified filename.
- apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode

- name: Install coding tools
  apt:
    pkg:
      - code # Visual Studio Code

- name: Install git
  apt:
    name: git
    state: latest
    update_cache: yes

- name: Update the repository cache and update package "nginx" to latest version using default release squeeze-backport
  apt:
    name: nginx
    state: latest
    update_cache: yes
