

# h
# cd <minim-home>
# tar xf MinimServer-0.8.5.2-linux-intel.tar.gz
# minimserver/bin/startd
#- name: Installing MinimServer


#- name: MinimServer | Download Setup
#  get_url:
#    url: http://jminim.com/brac/MinimServer-0.8.5.2-linux-intel.tar.gz
#    dest: ~/MinimWatch-0.8.5.2-linux-intel.tgz

#- name: MinimServer | Extract files
#  unarchive:
#    src: ~/MinimWatch-0.8.5.2-linux-intel.tgz
#    dest: /usr/local/minimserver
#- name: MinimServer | Create install dir
#  file:
#    path: /usr/local/minimserver
#    state: directory
#    mode: '0755'

- name: MinimServer | Download & install files
  unarchive:
    src: http://jminim.com/brac/MinimServer-0.8.5.2-linux-intel.tar.gz
    dest: /usr/local
    remote_src: yes

- name: MinimServer | Enable auto start
  command: /usr/local/minimserver/bin/setup enable_autostart
    
    
