# roles/k3s_dev_environment/tasks/03_configure_k3s_user.yml
- name: Create .kube directory for {{ k3s_dev_environment_dev_user }}
  ansible.builtin.file:
    path: "/home/{{ k3s_dev_environment_dev_user }}/.kube"
    state: directory
    owner: "{{ k3s_dev_environment_dev_user }}"
    group: "{{ k3s_dev_environment_dev_user }}" # Or user's primary group, obtained via a fact
    mode: '0700'

- name: Copy K3s kubeconfig to {{ k3s_dev_environment_dev_user }}'s .kube directory
  ansible.builtin.copy:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "/home/{{ k3s_dev_environment_dev_user }}/.kube/config"
    owner: "{{ k3s_dev_environment_dev_user }}"
    group: "{{ k3s_dev_environment_dev_user }}"
    mode: '0600'
    remote_src: yes

- name: Update KUBECONFIG path in {{ k3s_dev_environment_dev_user }}'s environment (.bashrc)
  ansible.builtin.lineinfile:
    path: "/home/{{ k3s_dev_environment_dev_user }}/.bashrc"
    line: "export KUBECONFIG=$HOME/.kube/config"
    regexp: "^export KUBECONFIG=" # Ensures only one such line
    create: true
    owner: "{{ k3s_dev_environment_dev_user }}"
    group: "{{ k3s_dev_environment_dev_user }}"
    mode: '0644'
  notify: UserReloginNeeded

- name: Reminder for user to re-login or source profile
  ansible.builtin.debug:
    msg: "User {{ k3s_dev_environment_dev_user }} may need to re-login or source their .bashrc for KUBECONFIG and other env vars to take effect."
  run_once: true # Show only once per play
  when: true # Always show this as a reminder after this task file
