# roles/k3s_dev_environment/tasks/07_install_tilt.yml
- name: Check if Tilt is installed
  ansible.builtin.stat:
    path: "{{ local_bin_path }}/tilt"
  register: tilt_stat

- name: Download and install Tilt {{ tilt_version }}
  when: not tilt_stat.stat.exists or ansible_check_mode
  block:
    - name: Download Tilt archive
      ansible.builtin.get_url:
        url: "https://github.com/tilt-dev/tilt/releases/download/v{{ tilt_version }}/tilt.{{ tilt_version }}.linux.x86_64.tar.gz"
        dest: "/tmp/tilt.{{ tilt_version }}.linux.x86_64.tar.gz"
        mode: '0644'
      register: tilt_archive_download
    - name: Extract Tilt binary directly to {{ local_bin_path }}
      ansible.builtin.unarchive:
        src: "{{ tilt_archive_download.dest }}"
        dest: "{{ local_bin_path }}" # Extracts 'tilt' binary into this dir
        remote_src: yes
        # extra_opts: [--no-same-owner] # May not be needed if dest owned by root
      args:
        creates: "{{ local_bin_path }}/tilt" # Idempotency: only if tilt isn't there
      when: tilt_archive_download is successful and tilt_archive_download.changed
      register: tilt_extract_status
    - name: Ensure Tilt binary is executable
      ansible.builtin.file:
        path: "{{ local_bin_path }}/tilt"
        mode: '0755'
        owner: root # Ensure root owns it
        group: root
      when: tilt_extract_status is successful and tilt_extract_status.changed
    - name: Clean up Tilt download
      ansible.builtin.file:
        path: "{{ tilt_archive_download.dest }}"
        state: absent
      when: tilt_archive_download.dest is defined
