# roles/k3s_dev_environment/vars/main.yml

# IMPORTANT: Set this to the non-root user you want to configure the environment for
# <<< CHANGE THIS to your actual Linux username
k3s_dev_environment_dev_user: "nicolas"
# <<< CHANGE THIS to your actual Windows username
k3s_dev_environment_windows_user: "nicolas.roquebert"

# Tool versions (verify latest stable versions when running)
k3s_dev_environment_k3s_version: "v1.33.1+k3s1"

# Should ideally match K3s major.minor
k3s_dev_environment_kubectl_version: "v1.33.0"
k3s_dev_environment_buildkit_version: "v0.22.0"
k3s_dev_environment_tilt_version: "0.35.0"

# K3s configuration
k3s_dev_environment_k3s_data_dir: "/var/lib/rancher/k3s"
k3s_dev_environment_k3s_install_args: >-
  --write-kubeconfig-mode 644
  --disable traefik
  --disable servicelb
  --node-name {{ ansible_hostname }}

# BuildKit configuration
k3s_dev_environment_buildkit_user: "buildkit"
k3s_dev_environment_buildkit_group: "buildkit"
k3s_dev_environment_buildkit_data_dir: "/var/lib/buildkit"
k3s_dev_environment_buildkit_socket_path: "unix:///run/buildkit/buildkitd.sock"
k3s_dev_environment_buildkit_tcp_addr: "tcp://127.0.0.1:1234" # For buildkitd to listen on

# Local Registry configuration
k3s_dev_environment_registry_namespace: "local-registry"
k3s_dev_environment_registry_deployment_name: "local-docker-registry" # Must match metadata.name in local-registry-k8s.yaml
k3s_dev_environment_registry_service_name: "local-registry-service"   # Must match metadata.name in local-registry-k8s.yaml
k3s_dev_environment_registry_image: "registry:2"
k3s_dev_environment_registry_node_port: 30500 # Port on the host to access the registry
k3s_dev_environment_registry_host_address: "localhost" # How BuildKit/Tilt will address the registry

# Tilt Sample Project
k3s_dev_environment_default_sample_lang: "go" # Options: go, typescript, python, csharp, rust, java
k3s_dev_environment_tilt_sample_app_dir_base: "/home" # Base directory for user's sample app
k3s_dev_environment_tilt_sample_app_name: "tilt_sample_app"
# Derived in tasks: tilt_sample_app_dir: "{{ tilt_sample_app_dir_base }}/{{ k3s_dev_environment_dev_user }}/{{ tilt_sample_app_name }}"
k3s_dev_environment_tilt_sample_image_name: "tilt-sample-app-image" # This placeholder is used in k8s-app.yaml and Tiltfile

# System paths
k3s_dev_environment_local_bin_path: "/usr/local/bin"

k3s_dev_environment_k3s_custom_exec_args: "server --advertise-address=0.0.0.0"
