---
# tasks file for roles/system_prerequisites_setup
- name: Ensure CA certificates are installed and updated
  ansible.builtin.apt:
    name: ca-certificates
    state: latest
    update_cache: true
  become: true

- name: Update certificate authority store
  command: update-ca-certificates
  become: true
...
