---
# tasks file for roles/coding_setup
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true

- name: Add an Apt signing key, will not download if present
  ansible.builtin.apt_key:
    # id: 9FED2BCBDCD29CDF762678CBAED4B06F473041FA
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VS Code repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode

- name: Install Visual Studio Code
  ansible.builtin.apt:
    pkg:
      - code
...
