- name: Install prerequisites for pyenv
  become: true
  apt:
    name:
      - build-essential
      - curl
      - git
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - llvm
      - make
      - tk-dev
      - wget
      - zlib1g-dev
      - libncursesw5-dev
      - xz-utils
    state: present
    update_cache: true

- name: Clone pyenv (under the user)
  git:
    repo: 'https://github.com/pyenv/pyenv.git'
    dest: "{{ ansible_env.HOME }}/.pyenv"
    version: master
  become: false

- name: Ensure pyenv environment is configured
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv init"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)"
  become: false

- name: Reload pyenv environment
  shell: |
    ~/.pyenv/bin/pyenv install -s 3.10.14
    ~/.pyenv/bin/pyenv global 3.10.14
  args:
    executable: /bin/bash
  environment:
    PYENV_ROOT: "{{ ansible_env.HOME }}/.pyenv"
    PATH: "{{ ansible_env.HOME }}/.pyenv/bin:{{ ansible_env.PATH }}"
  become: false

- name: Install Python and pip
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - libffi-dev
      - libssl-dev
      - gcc
      - make
    state: present
    update_cache: true
  become: true

- name: Upgrade pip for current user
  pip:
    name: pip
    state: latest
    extra_args: --user
    executable: pip3
  become: false
