---
# tasks file for roles/devops_setup
- name: Install required packages
  apt:
    name:
      - curl
      - git
      - unzip
    state: present
    update_cache: true
  become: true

#- name: Install ctlptl
#  import_tasks: ctlptl.yml

- name: Configure MOTD
  import_tasks: motd.yml

- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Install Terraform
  shell: |
    curl -fsSL https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip -o terraform.zip
    unzip terraform.zip
    mv terraform /usr/local/bin/
    rm terraform.zip
  args:
    creates: /usr/local/bin/terraform
...
