---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: python:3.10-slim
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      roles_path: /home/nicolas/ansible/roles
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
