---
# tasks file for roles/music
- name: Install abcm2ps and ghostscript
  ansible.builtin.apt:
    name:
      - abcm2ps
      - ghostscript
    state: present
    update_cache: true
  become: true
...
